// <auto-generated />
using System;
using Maliev.RegistryService.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Maliev.RegistryService.Data.Migrations
{
    [DbContext(typeof(RegistryDbContext))]
    partial class RegistryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Maliev.RegistryService.Data.Entities.ThaiLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DistrictEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DistrictTh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("ProvinceEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProvinceTh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubDistrictEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SubDistrictTh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictEn");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DistrictEn"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DistrictEn"), new[] { "gin_trgm_ops" });

                    b.HasIndex("DistrictTh");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("DistrictTh"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("DistrictTh"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PostalCode");

                    b.HasIndex("ProvinceEn");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProvinceEn"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProvinceEn"), new[] { "gin_trgm_ops" });

                    b.HasIndex("ProvinceTh");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("ProvinceTh"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("ProvinceTh"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SubDistrictEn");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SubDistrictEn"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SubDistrictEn"), new[] { "gin_trgm_ops" });

                    b.HasIndex("SubDistrictTh");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SubDistrictTh"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SubDistrictTh"), new[] { "gin_trgm_ops" });

                    b.ToTable("ThaiLocations");
                });
#pragma warning restore 612, 618
        }
    }
}
